package com.sio.firearms.registry;

import com.sio.firearms.Firearms;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModCreativeTabs {

    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Firearms.MOD_ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> FIREARMS_TAB =
            CREATIVE_MODE_TABS.register("firearms", () -> CreativeModeTab.builder()
                    .title(Component.literal("Firearms"))
                    .icon(() -> ModItems.STEEL_INGOT.get().getDefaultInstance())
                    .displayItems((parameters, output) -> {
                        output.accept(ModItems.STEEL_INGOT.get());
                        output.accept(ModItems.GUN_BARREL.get());
                        output.accept(ModItems.GUN_GRIP.get());
                        output.accept(ModItems.TRIGGER_ASSEMBLY.get());
                        output.accept(ModItems.MAGAZINE.get());
                        output.accept(ModItems.BULLET.get());
                        output.accept(ModItems.REFINED_GUNPOWDER.get());
                        output.accept(ModItems.REFINED_BULLET.get());
                        output.accept(ModItems.HARDENED_STEEL_INGOT.get());
                        output.accept(ModItems.PROPELLANT_POWDER.get());
                        output.accept(ModItems.STEEL_ROD.get());
                        output.accept(ModItems.GUN_BARREL_BLANK.get());
                        output.accept(ModItems.FIRING_MECHANISM.get());
                        output.accept(ModItems.BULLET_CASING.get());
                        output.accept(ModItems.LEAD_INGOT.get());
                        output.accept(ModItems.PISTOL.get());
                        output.accept(ModItems.RIFLE.get());
                        output.accept(ModItems.SHOTGUN.get());
                        output.accept(ModItems.SNIPER_RIFLE.get());
                        output.accept(ModItems.SMG.get());
                        output.accept(ModItems.RED_DOT.get());
                        output.accept(ModItems.HOLO_SIGHT.get());
                        output.accept(ModItems.LASER.get());
                        output.accept(ModItems.FLASHLIGHT.get());
                        output.accept(ModItems.SCOPE_4X.get());
                        output.accept(ModItems.SCOPE_8X.get());
                        output.accept(ModItems.METAL_PRESS.get());
                        output.accept(ModItems.GUN_MODIFICATION_TABLE.get());
                        output.accept(ModItems.CARBON_STEEL.get());
                        output.accept(ModItems.SPRING.get());
                        output.accept(ModItems.FIRING_PIN.get());
                        output.accept(ModItems.COAL_GENERATOR.get());
                        output.accept(ModItems.FUEL_GENERATOR.get());
                        output.accept(ModItems.HEAT_TREATMENT_FURNACE.get());
                        output.accept(ModItems.LATHE.get());
                        output.accept(ModItems.ASSEMBLY_BENCH.get());
                        output.accept(ModItems.ENERGY_PYLON.get());
                        output.accept(ModItems.COPPER_WIRE.get());
                        output.accept(ModItems.BATTERY.get());
                        output.accept(ModItems.RUBBER_SHEET.get());
                        output.accept(ModItems.GUN_OIL.get());
                        output.accept(ModItems.BOLT.get());
                        output.accept(ModItems.BUFFER_TUBE.get());
                        output.accept(ModItems.RUBBER_GRIP.get());
                        output.accept(ModItems.CLEANING_KIT.get());
                        output.accept(ModItems.INDUSTRIAL_LUBRICANT.get());
                        output.accept(ModItems.OIL_BUCKET.get());
                        output.accept(ModItems.FUEL_BUCKET.get());
                        output.accept(ModItems.REFINERY_BASE.get());
                        output.accept(ModItems.REFINERY_WALL.get());
                        output.accept(ModItems.REFINERY_TOP.get());
                        output.accept(ModItems.REFINERY_CONTROLLER.get());
                        output.accept(ModItems.ENERGY_PORT.get());
                        output.accept(ModItems.FLUID_PORT.get());
                        output.accept(ModItems.FLUID_PIPE.get());
                        output.accept(ModItems.ITEM_PIPE.get());
                        output.accept(ModItems.WEAPON_RACK.get());
                        output.accept(ModItems.OIL_DERRICK_BASE.get());
                        output.accept(ModItems.OIL_DERRICK_PILLAR.get());
                        output.accept(ModItems.OIL_DERRICK_CONTROLLER.get());
                        output.accept(ModItems.BANDAGE.get());
                        output.accept(ModItems.MEDIKIT.get());
                        output.accept(ModItems.KEVLAR_PLATE.get());
                        output.accept(ModItems.BULLETPROOF_VEST.get());
                        output.accept(ModItems.NIGHT_VISION_GOGGLES.get());
                        output.accept(ModItems.CIRCUIT_BOARD.get());
                        output.accept(ModItems.ELECTRONIC_TRIGGER.get());
                        output.accept(ModItems.AUTO_TURRET.get());
                        output.accept(ModItems.EXPLOSIVE_COMPOUND.get());
                        output.accept(ModItems.GRENADE.get());
                        output.accept(ModItems.SMOKE_GRENADE.get());
                        output.accept(ModItems.LAND_MINE.get());
                        output.accept(ModItems.SEA_MINE.get());
                        output.accept(ModItems.NITROGLYCERIN.get());
                        output.accept(ModItems.FLAMETHROWER.get());
                        output.accept(ModItems.MOLOTOV_COCKTAIL.get());
                        output.accept(ModItems.GAS_MASK.get());
                        output.accept(ModItems.WRENCH.get());
                        output.accept(ModItems.GOLD_FOIL.get());
                        output.accept(ModItems.DIAMOND_SAW_BLADE.get());
                        output.accept(ModItems.METALLURGICAL_SILICON.get());
                        output.accept(ModItems.ELECTRONIC_GRADE_SILICON.get());
                        output.accept(ModItems.SILICON_INGOT.get());
                        output.accept(ModItems.SILICON_WAFER.get());
                        output.accept(ModItems.COATED_WAFER.get());
                        output.accept(ModItems.PATTERNED_WAFER.get());
                        output.accept(ModItems.ETCHED_WAFER.get());
                        output.accept(ModItems.DOPED_WAFER.get());
                        output.accept(ModItems.FINISHED_WAFER.get());
                        output.accept(ModItems.TESTED_WAFER.get());
                        output.accept(ModItems.DEFECTIVE_WAFER.get());
                        output.accept(ModItems.SILICON_DIE.get());
                        output.accept(ModItems.BASIC_MICROCHIP.get());
                        output.accept(ModItems.ADVANCED_MICROCHIP.get());
                        output.accept(ModItems.PHOTOMASK.get());
                        output.accept(ModItems.COAL_COKE.get());
                        output.accept(ModItems.CREOSOTE_OIL_BUCKET.get());
                        output.accept(ModItems.COKE_OVEN_BRICK.get());
                        output.accept(ModItems.COKE_OVEN_CONTROLLER.get());
                        output.accept(ModItems.EBF_CONTROLLER.get());
                        output.accept(ModItems.BLAST_FURNACE_CASING.get());
                        output.accept(ModItems.MUFFLER_HATCH.get());
                        output.accept(ModItems.EBF_IMPORT_BUS.get());
                        output.accept(ModItems.EBF_OUTPUT_BUS.get());
                        output.accept(ModItems.CHEMICAL_MIXER.get());
                        output.accept(ModItems.CHEMICAL_MIXER_BASE.get());
                        output.accept(ModItems.CHEMICAL_MIXER_WALL.get());
                        output.accept(ModItems.CHEMICAL_MIXER_CONTROLLER.get());
                        output.accept(ModItems.ACID_BATH.get());
                        output.accept(ModItems.QUARTZ_SAND.get());
                        output.accept(ModItems.ETCHED_STEEL.get());
                        output.accept(ModItems.ETCHED_COPPER.get());
                        output.accept(ModItems.ETCHED_IRON.get());
                        output.accept(ModItems.SYNTHETIC_RUBBER.get());
                        output.accept(ModItems.SULFURIC_ACID_BUCKET.get());
                        output.accept(ModItems.NITRIC_ACID_BUCKET.get());
                        output.accept(ModItems.SYNTHETIC_RUBBER_BUCKET.get());
                        output.accept(ModItems.WATER_PUMP.get());
                        output.accept(ModItems.SULFUR_ORE.get());
                        output.accept(ModItems.SALTPETER_ORE.get());
                        output.accept(ModItems.TUNGSTEN_ORE.get());
                        output.accept(ModItems.FLUORITE_ORE.get());
                        output.accept(ModItems.URANIUM_ORE.get());
                        output.accept(ModItems.CHROMIUM_ORE.get());
                        output.accept(ModItems.NICKEL_ORE.get());
                        output.accept(ModItems.BAUXITE_ORE.get());
                        output.accept(ModItems.KANTHAL_COIL.get());
                        output.accept(ModItems.NICHROME_COIL.get());
                        output.accept(ModItems.TUNGSTEN_COIL.get());
                        output.accept(ModItems.SULFUR.get());
                        output.accept(ModItems.SALTPETER.get());
                        output.accept(ModItems.TUNGSTEN_ORE_RAW.get());
                        output.accept(ModItems.FLUORITE_CRYSTAL.get());
                        output.accept(ModItems.URANIUM_ORE_RAW.get());
                        output.accept(ModItems.TUNGSTEN_INGOT.get());
                        output.accept(ModItems.URANIUM_INGOT.get());
                        output.accept(ModItems.CHROMIUM_INGOT.get());
                        output.accept(ModItems.NICKEL_INGOT.get());
                        output.accept(ModItems.BAUXITE_DUST.get());
                        output.accept(ModItems.ALUMINUM_INGOT.get());
                        output.accept(ModItems.KANTHAL_ALLOY.get());
                        output.accept(ModItems.KANTHAL_WIRE.get());
                        output.accept(ModItems.NICHROME_ALLOY.get());
                        output.accept(ModItems.NICHROME_WIRE.get());
                        output.accept(ModItems.TUNGSTEN_CARBIDE.get());
                        output.accept(ModItems.TUNGSTEN_WIRE.get());
                        output.accept(ModItems.TUNGSTEN_ROD.get());
                        output.accept(ModItems.ARMOR_PIERCING_BULLET.get());
                        output.accept(ModItems.NITROCELLULOSE.get());
                        output.accept(ModItems.ELECTROLYSIS_MACHINE.get());
                        output.accept(ModItems.HYDROGEN_GAS_BUCKET.get());
                        output.accept(ModItems.OXYGEN_GAS_BUCKET.get());
                        output.accept(ModItems.FLUORINE_GAS_BUCKET.get());
                        output.accept(ModItems.CHLORINE_GAS_BUCKET.get());
                        output.accept(ModItems.NITRATE_SOLUTION_BUCKET.get());
                        output.accept(ModItems.PVC_RESIN_BUCKET.get());
                        output.accept(ModItems.PVC_PELLETS.get());
                        output.accept(ModItems.PLASTIC_SHEET.get());
                        output.accept(ModItems.PIPE_FITTING.get());
                        output.accept(ModItems.BUTANE_BUCKET.get());
                        output.accept(ModItems.GASOLINE_BUCKET.get());
                        output.accept(ModItems.NAPHTHA_BUCKET.get());
                        output.accept(ModItems.KEROSENE_BUCKET.get());
                        output.accept(ModItems.DIESEL_BUCKET.get());
                        output.accept(ModItems.HEAVY_GAS_OIL_BUCKET.get());
                        output.accept(ModItems.RESIDUAL_FUEL_OIL_BUCKET.get());
                        output.accept(ModItems.BORON.get());
                        output.accept(ModItems.PHOSPHORUS.get());
                        output.accept(ModItems.WAFER_CUTTING_MACHINE.get());
                        output.accept(ModItems.DEPOSITION_CHAMBER.get());
                        output.accept(ModItems.PLASMA_ETCHER.get());
                        output.accept(ModItems.ION_IMPLANTER.get());
                        output.accept(ModItems.METALLIZATION_CHAMBER.get());
                        output.accept(ModItems.WAFER_TESTER.get());
                        output.accept(ModItems.DICING_SAW.get());
                        output.accept(ModItems.CHIP_PACKAGING_MACHINE.get());
                        output.accept(ModItems.PHOTORESIST_BUCKET.get());
                        output.accept(ModItems.CRYSTAL_GROWTH_BASE.get());
                        output.accept(ModItems.CRYSTAL_GROWTH_WALL.get());
                        output.accept(ModItems.CRYSTAL_GROWTH_TOP.get());
                        output.accept(ModItems.CRYSTAL_GROWTH_CONTROLLER.get());
                        output.accept(ModItems.EUV_BASE.get());
                        output.accept(ModItems.EUV_WALL.get());
                        output.accept(ModItems.EUV_LENS_HOUSING.get());
                        output.accept(ModItems.EUV_MIRROR_ARRAY.get());
                        output.accept(ModItems.EUV_EMITTER_HOUSING.get());
                        output.accept(ModItems.EUV_LITHOGRAPHY_CONTROLLER.get());
                        // ── Nuclear Reactor Stage 1 ───────────────────────────
                        output.accept(ModItems.ZIRCONITE_ORE.get());
                        output.accept(ModItems.ZIRCONIUM_ORE_RAW.get());
                        output.accept(ModItems.ZIRCONIUM_INGOT.get());
                        output.accept(ModItems.URANIUM_HEXAFLUORIDE.get());
                        output.accept(ModItems.ENRICHED_URANIUM_HEXAFLUORIDE.get());
                        output.accept(ModItems.DEPLETED_URANIUM_HEXAFLUORIDE.get());
                        output.accept(ModItems.URANIUM_DIOXIDE_POWDER.get());
                        output.accept(ModItems.URANIUM_DIOXIDE_PELLET.get());
                        output.accept(ModItems.FUEL_ROD_CLADDING.get());
                        output.accept(ModItems.FUEL_ROD.get());
                        output.accept(ModItems.FUEL_ROD_ASSEMBLY.get());
                        output.accept(ModItems.SPENT_FUEL_ROD.get());
                        output.accept(ModItems.DEPLETED_URANIUM.get());
                        output.accept(ModItems.BORON_CARBIDE.get());
                        output.accept(ModItems.CONTROL_ROD.get());
                        output.accept(ModItems.GRAPHITE_BLOCK_ITEM.get());
                        output.accept(ModItems.URANIUM_HEXAFLUORIDE_BUCKET.get());
                        output.accept(ModItems.ENRICHED_UF6_BUCKET.get());
                        output.accept(ModItems.DEPLETED_UF6_BUCKET.get());
                        output.accept(ModItems.HEAVY_WATER_BUCKET.get());
                        output.accept(ModItems.STEAM_BUCKET.get());
                        output.accept(ModItems.GAS_CENTRIFUGE.get());
                        output.accept(ModItems.FLUID_TANK.get());
                        // Nuclear Reactor Stage 2
                        output.accept(ModItems.REACTOR_BASE.get());
                        output.accept(ModItems.REACTOR_WALL.get());
                        output.accept(ModItems.REACTOR_TOP.get());
                        output.accept(ModItems.REACTOR_CONTROL_ROD_HOUSING.get());
                        output.accept(ModItems.LEAD_BLOCK.get());
                        output.accept(ModItems.REACTOR_CONTROLLER.get());
                        output.accept(ModItems.STEAM_TURBINE.get());
                        // ── Cooling Tower ─────────────────────────────────────
                        output.accept(ModItems.COOLING_TOWER_BASE.get());
                        output.accept(ModItems.COOLING_TOWER_WALL.get());
                        output.accept(ModItems.COOLING_TOWER_VENT.get());
                        output.accept(ModItems.COOLING_TOWER_CONTROLLER.get());
                        output.accept(ModItems.HAZMAT_HELMET.get());
                        output.accept(ModItems.HAZMAT_CHESTPLATE.get());
                        output.accept(ModItems.HAZMAT_LEGGINGS.get());
                        output.accept(ModItems.HAZMAT_BOOTS.get());
                        output.accept(ModItems.GEIGER_COUNTER.get());
                        // ── Vehicle Garage ────────────────────────────────────
                        output.accept(ModItems.GARAGE_FLOOR.get());
                        output.accept(ModItems.GARAGE_WALL.get());
                        output.accept(ModItems.GARAGE_ROOF.get());
                        output.accept(ModItems.GARAGE_DOOR.get());
                        output.accept(ModItems.GARAGE_CONTROLLER.get());
                        output.accept(ModItems.TANK_SCHEMATIC.get());
                        // ── Tank Production Chain ─────────────────────────────
                        output.accept(ModItems.STEEL_PLATE.get());
                        output.accept(ModItems.TANK_HULL.get());
                        output.accept(ModItems.TANK_TRACKS.get());
                        output.accept(ModItems.TANK_TURRET.get());
                        output.accept(ModItems.DIESEL_ENGINE.get());
                        output.accept(ModItems.TANK_CANNON.get());
                        output.accept(ModItems.CRATE.get());
                        output.accept(ModItems.TRASH_CAN.get());
                        output.accept(ModItems.CHAINSAW.get());
                        output.accept(ModItems.MINIGUN.get());
                        output.accept(ModItems.AMMO_BOX.get());
                        output.accept(ModItems.GUN_CASE.get());
                        // ── Rubber Boots & Riot Shield ────────────────────────
                        output.accept(ModItems.RUBBER_BOOTS.get());
                        output.accept(ModItems.RIOT_SHIELD.get());
                        // ── Cordite & Military Grade Ammo ─────────────────────
                        output.accept(ModItems.CORDITE.get());
                        output.accept(ModItems.CORDITE_BULLET.get());
                        output.accept(ModItems.EXPLOSIVE_BULLET.get());
                        // ── Match Grade Ammunition ────────────────────────────
                        output.accept(ModItems.MATCH_GRADE_POWDER.get());
                        output.accept(ModItems.MATCH_GRADE_BULLET.get());
                        // ── Pharmaceutical ────────────────────────────────────
                        output.accept(ModItems.POPPY_SEEDS.get());
                        output.accept(ModItems.RAW_OPIUM.get());
                        output.accept(ModItems.REFINED_OPIUM.get());
                        output.accept(ModItems.MORPHINE.get());
                        output.accept(ModItems.ADRENALINE.get());
                        output.accept(ModItems.COAGULANT.get());
                        output.accept(ModItems.SYRINGE.get());
                        output.accept(ModItems.MORPHINE_SYRINGE.get());
                        output.accept(ModItems.ADRENALINE_SYRINGE.get());
                        output.accept(ModItems.COAGULANT_SYRINGE.get());
                        // ── Titanium / Iridium / Osmium ───────────────────────
                        output.accept(ModItems.TITANIUM_ORE.get());
                        output.accept(ModItems.IRIDIUM_ORE.get());
                        output.accept(ModItems.OSMIUM_ORE.get());
                        output.accept(ModItems.TITANIUM_ORE_RAW.get());
                        output.accept(ModItems.IRIDIUM_ORE_RAW.get());
                        output.accept(ModItems.OSMIUM_ORE_RAW.get());
                        output.accept(ModItems.TITANIUM_INGOT.get());
                        output.accept(ModItems.IRIDIUM_INGOT.get());
                        output.accept(ModItems.OSMIUM_INGOT.get());
                        output.accept(ModItems.IRIDIUM_ALLOY.get());
                        output.accept(ModItems.IRIDIUM_WIRE.get());
                        output.accept(ModItems.IRIDIUM_COIL.get());
                        // ── Spent Fuel Storage ────────────────────────────────
                        output.accept(ModItems.SPENT_FUEL_STORAGE_BASE.get());
                        output.accept(ModItems.SPENT_FUEL_STORAGE_WALL.get());
                        output.accept(ModItems.SPENT_FUEL_STORAGE_CONTROLLER.get());
                        // ── Titanium & Battlesuit ─────────────────────────────
                        output.accept(ModItems.TITANIUM_ORE.get());
                        output.accept(ModItems.TITANIUM_ORE_RAW.get());
                        output.accept(ModItems.TITANIUM_INGOT.get());
                        output.accept(ModItems.BATTLESUIT_HELMET.get());
                        output.accept(ModItems.BATTLESUIT_CHESTPLATE.get());
                        output.accept(ModItems.BATTLESUIT_LEGGINGS.get());
                        output.accept(ModItems.BATTLESUIT_BOOTS.get());
                        // ── Incendiary Weapons ────────────────────────────────
                        output.accept(ModItems.NAPALM_BOMB.get());
                        output.accept(ModItems.THERMITE_GRENADE.get());
                        // ── Aircraft Hangar ───────────────────────────────────
                        output.accept(ModItems.HANGAR_FLOOR.get());
                        output.accept(ModItems.HANGAR_WALL.get());
                        output.accept(ModItems.HANGAR_ROOF.get());
                        output.accept(ModItems.HANGAR_DOOR.get());
                        output.accept(ModItems.HANGAR_CONTROLLER.get());
                        // ── Aircraft Components ───────────────────────────────
                        output.accept(ModItems.AIRCRAFT_FUSELAGE.get());
                        output.accept(ModItems.AIRCRAFT_WINGS.get());
                        output.accept(ModItems.JET_ENGINE.get());
                        output.accept(ModItems.COCKPIT_AVIONICS.get());
                    })
                    .build());
}
